//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoOrdersIntake {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=OPTIMUM-MGN;Initial Catalog=Mobile_Optimum;Persist Security Info=True" +
            ";User ID=sa;Password=456123")]
        public string ConnStringOptimum {
            get {
                return ((string)(this["ConnStringOptimum"]));
            }
            set {
                this["ConnStringOptimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ISPRO7srv-mgn;Initial Catalog=dfirm002_gmk;Persist Security Info=True" +
            ";User ID=sa;Password=456123")]
        public string ConnStringISPRO {
            get {
                return ((string)(this["ConnStringISPRO"]));
            }
            set {
                this["ConnStringISPRO"] = value;
            }
        }
    }
}
